#ifndef __FLOW_VALIDATOR_BACKEND_CONSTANTS_H__
#define __FLOW_VALIDATOR_BACKEND_CONSTANTS_H__

#define CONTROLLER_PORT 0xFFFFFFFD
#define OUT_TO_IN_PORT 0xFFFFFFF8
#define LOCAL_PORT 0xFFFFFFFE

#endif