#!/bin/bash
sudo apt-get update -qq
sudo apt-get install -y docker.io
sudo docker build --no-cache --rm=true -t controller .
echo "Docker Built"
sudo docker run -t -i controller /bin/bash

container_id=`sudo docker ps -q`
sudo docker commit $container_id controller
sudo docker kill $container_id
cp Dockerfile .oldDockerfile
rm Dockerfile
cp Dockerfile2 Dockerfile
sudo docker build --no-cache -t opendaylight .
rm Dockerfile
cp .oldDockerfile Dockerfile
rm .oldDockerfile

