# Copyright (c) 2015 Schweitzer Engineering Laboratories, Inc.
# ------------------------------------------------------------------------------
# <auto-generated>
#     This code was generated by a tool.
#     Runtime Version:4.0.30319.42000
#     Output Created 11/4/2015 11:15:41 AM
#
#     Changes to this file may cause incorrect behavior and will be lost if
#     the code is regenerated.
# </auto-generated>
# ------------------------------------------------------------------------------
from __future__ import absolute_import
import json
import datetime


class BaseHttpAccess(object):
    entity_base_name = u""
    entity_odata_type = u""
    _session = None
    api_tree_path = u'default/config/'

    def __init__(self, session):
        self._session = session

    def read_single(self, item_id):
        entity_path = self.api_tree_path + self.entity_base_name + u"('" + item_id + u"')"
        response = self._session.get_data(entity_path)
        pyson_response = json.loads(response)
        object_type = pyson_response[u'@odata.type'] if u'@odata.type' in pyson_response else self.entity_odata_type
        result = _ResolveOdataType.getNewObject(object_type)
        result.from_pyson(pyson_response)
        return result

    def read_collection(self):
        collection_path = self.api_tree_path + self.entity_base_name 
        response = self._session.get_data(collection_path)
        pyson_response = json.loads(response)
        result = []
        raw_json_list = pyson_response[u'value']
        for pyson_object in raw_json_list:
            object_type = pyson_object[u'@odata.type'] if u'@odata.type' in pyson_object else self.entity_odata_type
            new_object = _ResolveOdataType.getNewObject(object_type)
            new_object.from_pyson(pyson_object)
            result.append(new_object)
        return result

    def create_single(self, item):
        json_string = item.to_json()
        collection_path = self.api_tree_path + self.entity_base_name
        response = self._session.post_data(collection_path, json_string)
        pyson_response = json.loads(response)
        object_type = pyson_response[u'@odata.type'] if u'@odata.type' in pyson_response else self.entity_odata_type
        result = _ResolveOdataType.getNewObject(object_type)
        result.from_pyson(pyson_response)
        return result

    def update_single(self, item, item_id):
        item_json = item.to_json()
        entity_path = self.api_tree_path + self.entity_base_name + u"('" + item_id + u"')"
        response = self._session.put_data(entity_path, item_json)
        return response

    def patch_single(self, item, item_id, update_key_list):
        item_pyson = item.to_pyson()
        patch = {}
        for key in update_key_list:
            patch[key] = item_pyson[key]
        entity_path = self.api_tree_path + self.entity_base_name + u"('" + item_id + u"')"
        json_string = json.dumps(patch, sort_keys=True, indent=4, separators=(u',', u': '))
        response = self._session.patch_data(entity_path, json_string)
        return response

    def delete_single(self, item_id):
        entity_path = self.api_tree_path + self.entity_base_name + u"('" + item_id + u"')"
        response = self._session.delete_data(entity_path)
        return response

#
# Containers and Entity Sets
#


class nodesHttpAccess(BaseHttpAccess):

    def __init__(self, session):
        super(nodesHttpAccess, self).__init__(session)
        self.entity_base_name = u"nodes"
        self.entity_odata_type = u"#Sel.Sel5056.TopologyManager.Nodes.ConfigNode"



class portsHttpAccess(BaseHttpAccess):

    def __init__(self, session):
        super(portsHttpAccess, self).__init__(session)
        self.entity_base_name = u"ports"
        self.entity_odata_type = u"#Sel.Sel5056.TopologyManager.Ports.ConfigPort"



class linksHttpAccess(BaseHttpAccess):

    def __init__(self, session):
        super(linksHttpAccess, self).__init__(session)
        self.entity_base_name = u"links"
        self.entity_odata_type = u"#Sel.Sel5056.TopologyManager.Links.ConfigLink"



class externalCertificateInfoHttpAccess(BaseHttpAccess):

    def __init__(self, session):
        super(externalCertificateInfoHttpAccess, self).__init__(session)
        self.entity_base_name = u"externalCertificateInfo"
        self.entity_odata_type = u"#Sel.Sel5056.Common.TrustAuthority.DataTreeObjects.ExternalCertificateInfo"



class eventTypesHttpAccess(BaseHttpAccess):

    def __init__(self, session):
        super(eventTypesHttpAccess, self).__init__(session)
        self.entity_base_name = u"eventTypes"
        self.entity_odata_type = u"#Sel.Sel5056.Common.DataBroker.Types.EventBus.EventType"



class eventCategoriesHttpAccess(BaseHttpAccess):

    def __init__(self, session):
        super(eventCategoriesHttpAccess, self).__init__(session)
        self.entity_base_name = u"eventCategories"
        self.entity_odata_type = u"#Sel.Sel5056.Common.DataBroker.Types.EventBus.EventCategory"



class flowsHttpAccess(BaseHttpAccess):

    def __init__(self, session):
        super(flowsHttpAccess, self).__init__(session)
        self.entity_base_name = u"flows"
        self.entity_odata_type = u"#Sel.Sel5056.OpenFlowPlugin.DataTreeObjects.Flow"



class groupsHttpAccess(BaseHttpAccess):

    def __init__(self, session):
        super(groupsHttpAccess, self).__init__(session)
        self.entity_base_name = u"groups"
        self.entity_odata_type = u"#Sel.Sel5056.OpenFlowPlugin.DataTreeObjects.Group"



class flowSetHttpAccess(BaseHttpAccess):

    def __init__(self, session):
        super(flowSetHttpAccess, self).__init__(session)
        self.entity_base_name = u"flowSet"
        self.entity_odata_type = u"#Sel.Sel5056.OpenFlowPlugin.DataTreeObjects.FlowSet"



class transactionsHttpAccess(BaseHttpAccess):

    def __init__(self, session):
        super(transactionsHttpAccess, self).__init__(session)
        self.entity_base_name = u"transactions"
        self.entity_odata_type = u"#Sel.Sel5056.Common.RestBroker.Models.RestTransaction"


#
#Begin Object Set Definition
#
# Odata Namespace Sel.Sel5056.Common.DataBroker.Types



class TypeKey(object):

    def __init__(self):
        self._odata_type = u'#Sel.Sel5056.Common.DataBroker.Types.TypeKey'
        self._full_key = u""
        self._category_key = u""
        self._event_type_key = u""

    def from_json(self, json_string):
        pyson_object = json.loads(json_string)
        self.from_pyson(pyson_object)
        return self

    def to_json(self):
        pyson_object = self.to_pyson()
        json_string = json.dumps(pyson_object, sort_keys=True, indent=4, separators=(u',', u': '))
        return json_string

    _full_key = None
    _category_key = None
    _event_type_key = None

    @property
    def full_key(self):
        return self._full_key

    @full_key.setter
    def full_key(self, value):
        self._full_key = value

    @property
    def category_key(self):
        return self._category_key

    @category_key.setter
    def category_key(self, value):
        self._category_key = value

    @property
    def event_type_key(self):
        return self._event_type_key

    @event_type_key.setter
    def event_type_key(self, value):
        self._event_type_key = value

    def to_pyson(self):
        pyson_object = {u'@odata.type': self._odata_type}
        self._add_pyson(pyson_object)
        return pyson_object

    def _add_pyson(self, pyson_object):
        pyson_object[u'fullKey'] = self._full_key
        pyson_object[u'categoryKey'] = self._category_key
        pyson_object[u'eventTypeKey'] = self._event_type_key
        return pyson_object

    def from_pyson(self,pyson_object):
        self._parse_pyson(pyson_object)
        return pyson_object

    def _parse_pyson(self, pyson_object):
        if u'fullKey' in pyson_object:
            self._full_key = pyson_object[u'fullKey']

        if u'categoryKey' in pyson_object:
            self._category_key = pyson_object[u'categoryKey']

        if u'eventTypeKey' in pyson_object:
            self._event_type_key = pyson_object[u'eventTypeKey']

        return pyson_object
# Odata Namespace Sel.Sel5056.OpenFlowPlugin.DataTreeObjects



class Bucket(object):

    def __init__(self):
        self._odata_type = u'#Sel.Sel5056.OpenFlowPlugin.DataTreeObjects.Bucket'
        self._id = u""
        self._watch_port = 0
        self._watch_group = 0
        self._actions = []

    def from_json(self, json_string):
        pyson_object = json.loads(json_string)
        self.from_pyson(pyson_object)
        return self

    def to_json(self):
        pyson_object = self.to_pyson()
        json_string = json.dumps(pyson_object, sort_keys=True, indent=4, separators=(u',', u': '))
        return json_string

    _id = None
    _watch_port = None
    _watch_group = None
    _actions = []

    @property
    def id(self):
        return self._id

    @id.setter
    def id(self, value):
        self._id = value

    @property
    def watch_port(self):
        return self._watch_port

    @watch_port.setter
    def watch_port(self, value):
        self._watch_port = value

    @property
    def watch_group(self):
        return self._watch_group

    @watch_group.setter
    def watch_group(self, value):
        self._watch_group = value

    @property
    def actions(self):
        return self._actions

    @actions.setter
    def actions(self, value):
        self._actions = value

    def to_pyson(self):
        pyson_object = {u'@odata.type': self._odata_type}
        self._add_pyson(pyson_object)
        return pyson_object

    def _add_pyson(self, pyson_object):
        pyson_object[u'id'] = self._id
        pyson_object[u'watchPort'] = self._watch_port
        pyson_object[u'watchGroup'] = self._watch_group
        #Complex Copy of actions
        actions_result = []
        for item_from_actions in self._actions:
            actions_result.append(item_from_actions.to_pyson())
        pyson_object[u'actions'] = actions_result
        return pyson_object

    def from_pyson(self,pyson_object):
        self._parse_pyson(pyson_object)
        return pyson_object

    def _parse_pyson(self, pyson_object):
        if u'id' in pyson_object:
            self._id = pyson_object[u'id']

        if u'watchPort' in pyson_object:
            self._watch_port = pyson_object[u'watchPort']

        if u'watchGroup' in pyson_object:
            self._watch_group = pyson_object[u'watchGroup']

        if u'actions' in pyson_object:
            self._actions = []
            actions_json_list = pyson_object[u'actions']
            for actions_json_element in actions_json_list:
                actions_odata_type = u'#Sel.Sel5056.OpenFlowPlugin.DataTreeObjects.Action'
                if u'@odata.type' in actions_json_element:
                    actions_odata_type = actions_json_element[u'@odata.type']
                new_element = _ResolveOdataType.getNewObject(actions_odata_type)
                new_element.from_pyson(actions_json_element)
                self._actions.append(new_element)
        return pyson_object


class Action(object):

    def __init__(self):
        self._odata_type = u'#Sel.Sel5056.OpenFlowPlugin.DataTreeObjects.Action'
        self._set_order = 0

    def from_json(self, json_string):
        pyson_object = json.loads(json_string)
        self.from_pyson(pyson_object)
        return self

    def to_json(self):
        pyson_object = self.to_pyson()
        json_string = json.dumps(pyson_object, sort_keys=True, indent=4, separators=(u',', u': '))
        return json_string

    _action_type = None
    _set_order = None

    @property
    def action_type(self):
        return self._action_type

    @action_type.setter
    def action_type(self, value):
        self._action_type = value

    @property
    def set_order(self):
        return self._set_order

    @set_order.setter
    def set_order(self, value):
        self._set_order = value

    def to_pyson(self):
        pyson_object = {u'@odata.type': self._odata_type}
        self._add_pyson(pyson_object)
        return pyson_object

    def _add_pyson(self, pyson_object):
        pyson_object[u'actionType'] = self._action_type
        pyson_object[u'setOrder'] = self._set_order
        return pyson_object

    def from_pyson(self,pyson_object):
        self._parse_pyson(pyson_object)
        return pyson_object

    def _parse_pyson(self, pyson_object):
        if u'actionType' in pyson_object:
            self._action_type = pyson_object[u'actionType']

        if u'setOrder' in pyson_object:
            self._set_order = pyson_object[u'setOrder']

        return pyson_object


class GroupAction(Action):

    def __init__(self):
        super(GroupAction, self).__init__()
        self._odata_type = u'#Sel.Sel5056.OpenFlowPlugin.DataTreeObjects.GroupAction'
        self._group_id = 0

    def from_json(self, json_string):
        pyson_object = json.loads(json_string)
        self.from_pyson(pyson_object)
        return self

    def to_json(self):
        pyson_object = self.to_pyson()
        json_string = json.dumps(pyson_object, sort_keys=True, indent=4, separators=(u',', u': '))
        return json_string

    _group_id = None

    @property
    def group_id(self):
        return self._group_id

    @group_id.setter
    def group_id(self, value):
        self._group_id = value

    def to_pyson(self):
        pyson_object = {u'@odata.type': self._odata_type}
        super(GroupAction, self)._add_pyson(pyson_object)
        self._add_pyson(pyson_object)
        return pyson_object

    def _add_pyson(self, pyson_object):
        pyson_object[u'groupId'] = self._group_id
        return pyson_object

    def from_pyson(self,pyson_object):
        super(GroupAction, self)._parse_pyson(pyson_object)
        self._parse_pyson(pyson_object)
        return pyson_object

    def _parse_pyson(self, pyson_object):
        if u'groupId' in pyson_object:
            self._group_id = pyson_object[u'groupId']

        return pyson_object


class OutputAction(Action):

    def __init__(self):
        super(OutputAction, self).__init__()
        self._odata_type = u'#Sel.Sel5056.OpenFlowPlugin.DataTreeObjects.OutputAction'
        self._out_port = 0
        self._max_length = 0

    def from_json(self, json_string):
        pyson_object = json.loads(json_string)
        self.from_pyson(pyson_object)
        return self

    def to_json(self):
        pyson_object = self.to_pyson()
        json_string = json.dumps(pyson_object, sort_keys=True, indent=4, separators=(u',', u': '))
        return json_string

    _out_port = None
    _max_length = None

    @property
    def out_port(self):
        return self._out_port

    @out_port.setter
    def out_port(self, value):
        self._out_port = value

    @property
    def max_length(self):
        return self._max_length

    @max_length.setter
    def max_length(self, value):
        self._max_length = value

    def to_pyson(self):
        pyson_object = {u'@odata.type': self._odata_type}
        super(OutputAction, self)._add_pyson(pyson_object)
        self._add_pyson(pyson_object)
        return pyson_object

    def _add_pyson(self, pyson_object):
        pyson_object[u'outPort'] = self._out_port
        pyson_object[u'maxLength'] = self._max_length
        return pyson_object

    def from_pyson(self,pyson_object):
        super(OutputAction, self)._parse_pyson(pyson_object)
        self._parse_pyson(pyson_object)
        return pyson_object

    def _parse_pyson(self, pyson_object):
        if u'outPort' in pyson_object:
            self._out_port = pyson_object[u'outPort']

        if u'maxLength' in pyson_object:
            self._max_length = pyson_object[u'maxLength']

        return pyson_object


class PushVlanAction(Action):

    def __init__(self):
        super(PushVlanAction, self).__init__()
        self._odata_type = u'#Sel.Sel5056.OpenFlowPlugin.DataTreeObjects.PushVlanAction'
        self._ether_type = 0

    def from_json(self, json_string):
        pyson_object = json.loads(json_string)
        self.from_pyson(pyson_object)
        return self

    def to_json(self):
        pyson_object = self.to_pyson()
        json_string = json.dumps(pyson_object, sort_keys=True, indent=4, separators=(u',', u': '))
        return json_string

    _ether_type = None

    @property
    def ether_type(self):
        return self._ether_type

    @ether_type.setter
    def ether_type(self, value):
        self._ether_type = value

    def to_pyson(self):
        pyson_object = {u'@odata.type': self._odata_type}
        super(PushVlanAction, self)._add_pyson(pyson_object)
        self._add_pyson(pyson_object)
        return pyson_object

    def _add_pyson(self, pyson_object):
        pyson_object[u'etherType'] = self._ether_type
        return pyson_object

    def from_pyson(self,pyson_object):
        super(PushVlanAction, self)._parse_pyson(pyson_object)
        self._parse_pyson(pyson_object)
        return pyson_object

    def _parse_pyson(self, pyson_object):
        if u'etherType' in pyson_object:
            self._ether_type = pyson_object[u'etherType']

        return pyson_object


class PopVlanAction(Action):

    def __init__(self):
        super(PopVlanAction, self).__init__()
        self._odata_type = u'#Sel.Sel5056.OpenFlowPlugin.DataTreeObjects.PopVlanAction'

    def from_json(self, json_string):
        pyson_object = json.loads(json_string)
        self.from_pyson(pyson_object)
        return self

    def to_json(self):
        pyson_object = self.to_pyson()
        json_string = json.dumps(pyson_object, sort_keys=True, indent=4, separators=(u',', u': '))
        return json_string


    def to_pyson(self):
        pyson_object = {u'@odata.type': self._odata_type}
        super(PopVlanAction, self)._add_pyson(pyson_object)
        self._add_pyson(pyson_object)
        return pyson_object

    def _add_pyson(self, pyson_object):
        return pyson_object

    def from_pyson(self,pyson_object):
        super(PopVlanAction, self)._parse_pyson(pyson_object)
        self._parse_pyson(pyson_object)
        return pyson_object

    def _parse_pyson(self, pyson_object):
        return pyson_object


class Match(object):

    def __init__(self):
        self._odata_type = u'#Sel.Sel5056.OpenFlowPlugin.DataTreeObjects.Match'
        self._in_port = None
        self._eth_dst = None
        self._eth_src = None
        self._ipv4_dst = None
        self._ipv4_src = None
        self._eth_type = None
        self._tcp_src = None
        self._tcp_dst = None
        self._udp_src = None
        self._udp_dst = None
        self._vlan_vid = None
        self._vlan_pcp = None
        self._ip_proto = None

    def from_json(self, json_string):
        pyson_object = json.loads(json_string)
        self.from_pyson(pyson_object)
        return self

    def to_json(self):
        pyson_object = self.to_pyson()
        json_string = json.dumps(pyson_object, sort_keys=True, indent=4, separators=(u',', u': '))
        return json_string

    _in_port = None
    _eth_dst = None
    _eth_src = None
    _ipv4_dst = None
    _ipv4_src = None
    _eth_type = None
    _tcp_src = None
    _tcp_dst = None
    _udp_src = None
    _udp_dst = None
    _vlan_vid = None
    _vlan_pcp = None
    _ip_proto = None

    @property
    def in_port(self):
        return self._in_port

    @in_port.setter
    def in_port(self, value):
        self._in_port = value

    @property
    def eth_dst(self):
        return self._eth_dst

    @eth_dst.setter
    def eth_dst(self, value):
        self._eth_dst = value

    @property
    def eth_src(self):
        return self._eth_src

    @eth_src.setter
    def eth_src(self, value):
        self._eth_src = value

    @property
    def ipv4_dst(self):
        return self._ipv4_dst

    @ipv4_dst.setter
    def ipv4_dst(self, value):
        self._ipv4_dst = value

    @property
    def ipv4_src(self):
        return self._ipv4_src

    @ipv4_src.setter
    def ipv4_src(self, value):
        self._ipv4_src = value

    @property
    def eth_type(self):
        return self._eth_type

    @eth_type.setter
    def eth_type(self, value):
        self._eth_type = value

    @property
    def tcp_src(self):
        return self._tcp_src

    @tcp_src.setter
    def tcp_src(self, value):
        self._tcp_src = value

    @property
    def tcp_dst(self):
        return self._tcp_dst

    @tcp_dst.setter
    def tcp_dst(self, value):
        self._tcp_dst = value

    @property
    def udp_src(self):
        return self._udp_src

    @udp_src.setter
    def udp_src(self, value):
        self._udp_src = value

    @property
    def udp_dst(self):
        return self._udp_dst

    @udp_dst.setter
    def udp_dst(self, value):
        self._udp_dst = value

    @property
    def vlan_vid(self):
        return self._vlan_vid

    @vlan_vid.setter
    def vlan_vid(self, value):
        self._vlan_vid = value

    @property
    def vlan_pcp(self):
        return self._vlan_pcp

    @vlan_pcp.setter
    def vlan_pcp(self, value):
        self._vlan_pcp = value

    @property
    def ip_proto(self):
        return self._ip_proto

    @ip_proto.setter
    def ip_proto(self, value):
        self._ip_proto = value

    def to_pyson(self):
        pyson_object = {u'@odata.type': self._odata_type}
        self._add_pyson(pyson_object)
        return pyson_object

    def _add_pyson(self, pyson_object):
        pyson_object[u'inPort'] = self._in_port
        pyson_object[u'ethDst'] = self._eth_dst
        pyson_object[u'ethSrc'] = self._eth_src
        pyson_object[u'ipv4Dst'] = self._ipv4_dst
        pyson_object[u'ipv4Src'] = self._ipv4_src
        pyson_object[u'ethType'] = self._eth_type
        pyson_object[u'tcpSrc'] = self._tcp_src
        pyson_object[u'tcpDst'] = self._tcp_dst
        pyson_object[u'udpSrc'] = self._udp_src
        pyson_object[u'udpDst'] = self._udp_dst
        pyson_object[u'vlanVid'] = self._vlan_vid
        pyson_object[u'vlanPcp'] = self._vlan_pcp
        pyson_object[u'ipProto'] = self._ip_proto
        return pyson_object

    def from_pyson(self,pyson_object):
        self._parse_pyson(pyson_object)
        return pyson_object

    def _parse_pyson(self, pyson_object):
        if u'inPort' in pyson_object:
            self._in_port = pyson_object[u'inPort']

        if u'ethDst' in pyson_object:
            self._eth_dst = pyson_object[u'ethDst']

        if u'ethSrc' in pyson_object:
            self._eth_src = pyson_object[u'ethSrc']

        if u'ipv4Dst' in pyson_object:
            self._ipv4_dst = pyson_object[u'ipv4Dst']

        if u'ipv4Src' in pyson_object:
            self._ipv4_src = pyson_object[u'ipv4Src']

        if u'ethType' in pyson_object:
            self._eth_type = pyson_object[u'ethType']

        if u'tcpSrc' in pyson_object:
            self._tcp_src = pyson_object[u'tcpSrc']

        if u'tcpDst' in pyson_object:
            self._tcp_dst = pyson_object[u'tcpDst']

        if u'udpSrc' in pyson_object:
            self._udp_src = pyson_object[u'udpSrc']

        if u'udpDst' in pyson_object:
            self._udp_dst = pyson_object[u'udpDst']

        if u'vlanVid' in pyson_object:
            self._vlan_vid = pyson_object[u'vlanVid']

        if u'vlanPcp' in pyson_object:
            self._vlan_pcp = pyson_object[u'vlanPcp']

        if u'ipProto' in pyson_object:
            self._ip_proto = pyson_object[u'ipProto']

        return pyson_object


class Instruction(object):

    def __init__(self):
        self._odata_type = u'#Sel.Sel5056.OpenFlowPlugin.DataTreeObjects.Instruction'
        self._actions = []

    def from_json(self, json_string):
        pyson_object = json.loads(json_string)
        self.from_pyson(pyson_object)
        return self

    def to_json(self):
        pyson_object = self.to_pyson()
        json_string = json.dumps(pyson_object, sort_keys=True, indent=4, separators=(u',', u': '))
        return json_string

    _instruction_type = None
    _actions = []

    @property
    def instruction_type(self):
        return self._instruction_type

    @instruction_type.setter
    def instruction_type(self, value):
        self._instruction_type = value

    @property
    def actions(self):
        return self._actions

    @actions.setter
    def actions(self, value):
        self._actions = value

    def to_pyson(self):
        pyson_object = {u'@odata.type': self._odata_type}
        self._add_pyson(pyson_object)
        return pyson_object

    def _add_pyson(self, pyson_object):
        pyson_object[u'instructionType'] = self._instruction_type
        #Complex Copy of actions
        actions_result = []
        for item_from_actions in self._actions:
            actions_result.append(item_from_actions.to_pyson())
        pyson_object[u'actions'] = actions_result
        return pyson_object

    def from_pyson(self,pyson_object):
        self._parse_pyson(pyson_object)
        return pyson_object

    def _parse_pyson(self, pyson_object):
        if u'instructionType' in pyson_object:
            self._instruction_type = pyson_object[u'instructionType']

        if u'actions' in pyson_object:
            self._actions = []
            actions_json_list = pyson_object[u'actions']
            for actions_json_element in actions_json_list:
                actions_odata_type = u'#Sel.Sel5056.OpenFlowPlugin.DataTreeObjects.Action'
                if u'@odata.type' in actions_json_element:
                    actions_odata_type = actions_json_element[u'@odata.type']
                new_element = _ResolveOdataType.getNewObject(actions_odata_type)
                new_element.from_pyson(actions_json_element)
                self._actions.append(new_element)
        return pyson_object


class ApplyActions(Instruction):

    def __init__(self):
        super(ApplyActions, self).__init__()
        self._odata_type = u'#Sel.Sel5056.OpenFlowPlugin.DataTreeObjects.ApplyActions'

    def from_json(self, json_string):
        pyson_object = json.loads(json_string)
        self.from_pyson(pyson_object)
        return self

    def to_json(self):
        pyson_object = self.to_pyson()
        json_string = json.dumps(pyson_object, sort_keys=True, indent=4, separators=(u',', u': '))
        return json_string


    def to_pyson(self):
        pyson_object = {u'@odata.type': self._odata_type}
        super(ApplyActions, self)._add_pyson(pyson_object)
        self._add_pyson(pyson_object)
        return pyson_object

    def _add_pyson(self, pyson_object):
        return pyson_object

    def from_pyson(self,pyson_object):
        super(ApplyActions, self)._parse_pyson(pyson_object)
        self._parse_pyson(pyson_object)
        return pyson_object

    def _parse_pyson(self, pyson_object):
        return pyson_object


class GoToTable(Instruction):

    def __init__(self):
        super(GoToTable, self).__init__()
        self._odata_type = u'#Sel.Sel5056.OpenFlowPlugin.DataTreeObjects.GoToTable'
        self._table_id = 0

    def from_json(self, json_string):
        pyson_object = json.loads(json_string)
        self.from_pyson(pyson_object)
        return self

    def to_json(self):
        pyson_object = self.to_pyson()
        json_string = json.dumps(pyson_object, sort_keys=True, indent=4, separators=(u',', u': '))
        return json_string

    _table_id = None

    @property
    def table_id(self):
        return self._table_id

    @table_id.setter
    def table_id(self, value):
        self._table_id = value

    def to_pyson(self):
        pyson_object = {u'@odata.type': self._odata_type}
        super(GoToTable, self)._add_pyson(pyson_object)
        self._add_pyson(pyson_object)
        return pyson_object

    def _add_pyson(self, pyson_object):
        pyson_object[u'tableId'] = self._table_id
        return pyson_object

    def from_pyson(self,pyson_object):
        super(GoToTable, self)._parse_pyson(pyson_object)
        self._parse_pyson(pyson_object)
        return pyson_object

    def _parse_pyson(self, pyson_object):
        if u'tableId' in pyson_object:
            self._table_id = pyson_object[u'tableId']

        return pyson_object


class WriteActions(Instruction):

    def __init__(self):
        super(WriteActions, self).__init__()
        self._odata_type = u'#Sel.Sel5056.OpenFlowPlugin.DataTreeObjects.WriteActions'

    def from_json(self, json_string):
        pyson_object = json.loads(json_string)
        self.from_pyson(pyson_object)
        return self

    def to_json(self):
        pyson_object = self.to_pyson()
        json_string = json.dumps(pyson_object, sort_keys=True, indent=4, separators=(u',', u': '))
        return json_string


    def to_pyson(self):
        pyson_object = {u'@odata.type': self._odata_type}
        super(WriteActions, self)._add_pyson(pyson_object)
        self._add_pyson(pyson_object)
        return pyson_object

    def _add_pyson(self, pyson_object):
        return pyson_object

    def from_pyson(self,pyson_object):
        super(WriteActions, self)._parse_pyson(pyson_object)
        self._parse_pyson(pyson_object)
        return pyson_object

    def _parse_pyson(self, pyson_object):
        return pyson_object


class Flow(object):

    def __init__(self):
        self._odata_type = u'#Sel.Sel5056.OpenFlowPlugin.DataTreeObjects.Flow'
        self._node = u""
        self._cookie = 0
        self._table_id = 0
        self._buffer_id = 0
        self._out_group = 0
        self._out_port = 0
        self._priority = 0
        self._match = Match()
        self._instructions = []
        self._enabled = False
        self._id = u""

    def from_json(self, json_string):
        pyson_object = json.loads(json_string)
        self.from_pyson(pyson_object)
        return self

    def to_json(self):
        pyson_object = self.to_pyson()
        json_string = json.dumps(pyson_object, sort_keys=True, indent=4, separators=(u',', u': '))
        return json_string

    _node = None
    _cookie = None
    _table_id = None
    _buffer_id = None
    _out_group = None
    _out_port = None
    _priority = None
    _match = None
    _instructions = []
    _enabled = None
    _id = None

    @property
    def node(self):
        return self._node

    @node.setter
    def node(self, value):
        self._node = value

    @property
    def cookie(self):
        return self._cookie

    @cookie.setter
    def cookie(self, value):
        self._cookie = value

    @property
    def table_id(self):
        return self._table_id

    @table_id.setter
    def table_id(self, value):
        self._table_id = value

    @property
    def buffer_id(self):
        return self._buffer_id

    @buffer_id.setter
    def buffer_id(self, value):
        self._buffer_id = value

    @property
    def out_group(self):
        return self._out_group

    @out_group.setter
    def out_group(self, value):
        self._out_group = value

    @property
    def out_port(self):
        return self._out_port

    @out_port.setter
    def out_port(self, value):
        self._out_port = value

    @property
    def priority(self):
        return self._priority

    @priority.setter
    def priority(self, value):
        self._priority = value

    @property
    def match(self):
        return self._match

    @match.setter
    def match(self, value):
        self._match = value

    @property
    def instructions(self):
        return self._instructions

    @instructions.setter
    def instructions(self, value):
        self._instructions = value

    @property
    def enabled(self):
        return self._enabled

    @enabled.setter
    def enabled(self, value):
        self._enabled = value

    @property
    def id(self):
        return self._id

    @id.setter
    def id(self, value):
        self._id = value

    def to_pyson(self):
        pyson_object = {u'@odata.type': self._odata_type}
        self._add_pyson(pyson_object)
        return pyson_object

    def _add_pyson(self, pyson_object):
        pyson_object[u'node'] = self._node
        pyson_object[u'cookie'] = self._cookie
        pyson_object[u'tableId'] = self._table_id
        pyson_object[u'bufferId'] = self._buffer_id
        pyson_object[u'outGroup'] = self._out_group
        pyson_object[u'outPort'] = self._out_port
        pyson_object[u'priority'] = self._priority
        pyson_object[u'match'] = self._match.to_pyson()
        #Complex Copy of instructions
        instructions_result = []
        for item_from_instructions in self._instructions:
            instructions_result.append(item_from_instructions.to_pyson())
        pyson_object[u'instructions'] = instructions_result
        pyson_object[u'enabled'] = self._enabled
        pyson_object[u'id'] = self._id
        return pyson_object

    def from_pyson(self,pyson_object):
        self._parse_pyson(pyson_object)
        return pyson_object

    def _parse_pyson(self, pyson_object):
        if u'node' in pyson_object:
            self._node = pyson_object[u'node']

        if u'cookie' in pyson_object:
            self._cookie = pyson_object[u'cookie']

        if u'tableId' in pyson_object:
            self._table_id = pyson_object[u'tableId']

        if u'bufferId' in pyson_object:
            self._buffer_id = pyson_object[u'bufferId']

        if u'outGroup' in pyson_object:
            self._out_group = pyson_object[u'outGroup']

        if u'outPort' in pyson_object:
            self._out_port = pyson_object[u'outPort']

        if u'priority' in pyson_object:
            self._priority = pyson_object[u'priority']

        if u'match' in pyson_object:
            self._match = Match()
            self._match.from_pyson(pyson_object[u'match'])

        if u'instructions' in pyson_object:
            self._instructions = []
            instructions_json_list = pyson_object[u'instructions']
            for instructions_json_element in instructions_json_list:
                instructions_odata_type = u'#Sel.Sel5056.OpenFlowPlugin.DataTreeObjects.Instruction'
                if u'@odata.type' in instructions_json_element:
                    instructions_odata_type = instructions_json_element[u'@odata.type']
                new_element = _ResolveOdataType.getNewObject(instructions_odata_type)
                new_element.from_pyson(instructions_json_element)
                self._instructions.append(new_element)
        if u'enabled' in pyson_object:
            self._enabled = pyson_object[u'enabled']

        if u'id' in pyson_object:
            self._id = pyson_object[u'id']

        return pyson_object


class Group(object):

    def __init__(self):
        self._odata_type = u'#Sel.Sel5056.OpenFlowPlugin.DataTreeObjects.Group'
        self._node = u""
        self._buckets = []
        self._group_id = 0
        self._id = u""

    def from_json(self, json_string):
        pyson_object = json.loads(json_string)
        self.from_pyson(pyson_object)
        return self

    def to_json(self):
        pyson_object = self.to_pyson()
        json_string = json.dumps(pyson_object, sort_keys=True, indent=4, separators=(u',', u': '))
        return json_string

    _node = None
    _buckets = []
    _group_type = None
    _group_id = None
    _id = None

    @property
    def node(self):
        return self._node

    @node.setter
    def node(self, value):
        self._node = value

    @property
    def buckets(self):
        return self._buckets

    @buckets.setter
    def buckets(self, value):
        self._buckets = value

    @property
    def group_type(self):
        return self._group_type

    @group_type.setter
    def group_type(self, value):
        self._group_type = value

    @property
    def group_id(self):
        return self._group_id

    @group_id.setter
    def group_id(self, value):
        self._group_id = value

    @property
    def id(self):
        return self._id

    @id.setter
    def id(self, value):
        self._id = value

    def to_pyson(self):
        pyson_object = {u'@odata.type': self._odata_type}
        self._add_pyson(pyson_object)
        return pyson_object

    def _add_pyson(self, pyson_object):
        pyson_object[u'node'] = self._node
        #Complex Copy of buckets
        buckets_result = []
        for item_from_buckets in self._buckets:
            buckets_result.append(item_from_buckets.to_pyson())
        pyson_object[u'buckets'] = buckets_result
        pyson_object[u'groupType'] = self._group_type
        pyson_object[u'groupId'] = self._group_id
        pyson_object[u'id'] = self._id
        return pyson_object

    def from_pyson(self,pyson_object):
        self._parse_pyson(pyson_object)
        return pyson_object

    def _parse_pyson(self, pyson_object):
        if u'node' in pyson_object:
            self._node = pyson_object[u'node']

        if u'buckets' in pyson_object:
            self._buckets = []
            buckets_json_list = pyson_object[u'buckets']
            for buckets_json_element in buckets_json_list:
                buckets_odata_type = u'#Sel.Sel5056.OpenFlowPlugin.DataTreeObjects.Bucket'
                if u'@odata.type' in buckets_json_element:
                    buckets_odata_type = buckets_json_element[u'@odata.type']
                new_element = _ResolveOdataType.getNewObject(buckets_odata_type)
                new_element.from_pyson(buckets_json_element)
                self._buckets.append(new_element)
        if u'groupType' in pyson_object:
            self._group_type = pyson_object[u'groupType']

        if u'groupId' in pyson_object:
            self._group_id = pyson_object[u'groupId']

        if u'id' in pyson_object:
            self._id = pyson_object[u'id']

        return pyson_object


class FlowSet(object):

    def __init__(self):
        self._odata_type = u'#Sel.Sel5056.OpenFlowPlugin.DataTreeObjects.FlowSet'
        self._id = u""

    def from_json(self, json_string):
        pyson_object = json.loads(json_string)
        self.from_pyson(pyson_object)
        return self

    def to_json(self):
        pyson_object = self.to_pyson()
        json_string = json.dumps(pyson_object, sort_keys=True, indent=4, separators=(u',', u': '))
        return json_string

    _id = None

    @property
    def id(self):
        return self._id

    @id.setter
    def id(self, value):
        self._id = value

    def to_pyson(self):
        pyson_object = {u'@odata.type': self._odata_type}
        self._add_pyson(pyson_object)
        return pyson_object

    def _add_pyson(self, pyson_object):
        pyson_object[u'id'] = self._id
        return pyson_object

    def from_pyson(self,pyson_object):
        self._parse_pyson(pyson_object)
        return pyson_object

    def _parse_pyson(self, pyson_object):
        if u'id' in pyson_object:
            self._id = pyson_object[u'id']

        return pyson_object
# Odata Namespace Sel.Sel5056.TopologyManager.Nodes



class ConfigNode(object):

    def __init__(self):
        self._odata_type = u'#Sel.Sel5056.TopologyManager.Nodes.ConfigNode'
        self._display_name = u""
        self._id = u""
        self._linked_key = u""

    def from_json(self, json_string):
        pyson_object = json.loads(json_string)
        self.from_pyson(pyson_object)
        return self

    def to_json(self):
        pyson_object = self.to_pyson()
        json_string = json.dumps(pyson_object, sort_keys=True, indent=4, separators=(u',', u': '))
        return json_string

    _display_name = None
    _state = None
    _id = None
    _linked_key = None

    @property
    def display_name(self):
        return self._display_name

    @display_name.setter
    def display_name(self, value):
        self._display_name = value

    @property
    def state(self):
        return self._state

    @state.setter
    def state(self, value):
        self._state = value

    @property
    def id(self):
        return self._id

    @id.setter
    def id(self, value):
        self._id = value

    @property
    def linked_key(self):
        return self._linked_key

    @linked_key.setter
    def linked_key(self, value):
        self._linked_key = value

    def to_pyson(self):
        pyson_object = {u'@odata.type': self._odata_type}
        self._add_pyson(pyson_object)
        return pyson_object

    def _add_pyson(self, pyson_object):
        pyson_object[u'displayName'] = self._display_name
        pyson_object[u'state'] = self._state
        pyson_object[u'id'] = self._id
        pyson_object[u'linkedKey'] = self._linked_key
        return pyson_object

    def from_pyson(self,pyson_object):
        self._parse_pyson(pyson_object)
        return pyson_object

    def _parse_pyson(self, pyson_object):
        if u'displayName' in pyson_object:
            self._display_name = pyson_object[u'displayName']

        if u'state' in pyson_object:
            self._state = pyson_object[u'state']

        if u'id' in pyson_object:
            self._id = pyson_object[u'id']

        if u'linkedKey' in pyson_object:
            self._linked_key = pyson_object[u'linkedKey']

        return pyson_object
# Odata Namespace Sel.Sel5056.TopologyManager.Ports



class ConfigPort(object):

    def __init__(self):
        self._odata_type = u'#Sel.Sel5056.TopologyManager.Ports.ConfigPort'
        self._display_name = u""
        self._id = u""
        self._linked_key = u""

    def from_json(self, json_string):
        pyson_object = json.loads(json_string)
        self.from_pyson(pyson_object)
        return self

    def to_json(self):
        pyson_object = self.to_pyson()
        json_string = json.dumps(pyson_object, sort_keys=True, indent=4, separators=(u',', u': '))
        return json_string

    _display_name = None
    _state = None
    _id = None
    _linked_key = None

    @property
    def display_name(self):
        return self._display_name

    @display_name.setter
    def display_name(self, value):
        self._display_name = value

    @property
    def state(self):
        return self._state

    @state.setter
    def state(self, value):
        self._state = value

    @property
    def id(self):
        return self._id

    @id.setter
    def id(self, value):
        self._id = value

    @property
    def linked_key(self):
        return self._linked_key

    @linked_key.setter
    def linked_key(self, value):
        self._linked_key = value

    def to_pyson(self):
        pyson_object = {u'@odata.type': self._odata_type}
        self._add_pyson(pyson_object)
        return pyson_object

    def _add_pyson(self, pyson_object):
        pyson_object[u'displayName'] = self._display_name
        pyson_object[u'state'] = self._state
        pyson_object[u'id'] = self._id
        pyson_object[u'linkedKey'] = self._linked_key
        return pyson_object

    def from_pyson(self,pyson_object):
        self._parse_pyson(pyson_object)
        return pyson_object

    def _parse_pyson(self, pyson_object):
        if u'displayName' in pyson_object:
            self._display_name = pyson_object[u'displayName']

        if u'state' in pyson_object:
            self._state = pyson_object[u'state']

        if u'id' in pyson_object:
            self._id = pyson_object[u'id']

        if u'linkedKey' in pyson_object:
            self._linked_key = pyson_object[u'linkedKey']

        return pyson_object
# Odata Namespace Sel.Sel5056.TopologyManager.Links



class ConfigLink(object):

    def __init__(self):
        self._odata_type = u'#Sel.Sel5056.TopologyManager.Links.ConfigLink'
        self._display_name = u""
        self._id = u""
        self._linked_key = u""

    def from_json(self, json_string):
        pyson_object = json.loads(json_string)
        self.from_pyson(pyson_object)
        return self

    def to_json(self):
        pyson_object = self.to_pyson()
        json_string = json.dumps(pyson_object, sort_keys=True, indent=4, separators=(u',', u': '))
        return json_string

    _display_name = None
    _state = None
    _id = None
    _linked_key = None

    @property
    def display_name(self):
        return self._display_name

    @display_name.setter
    def display_name(self, value):
        self._display_name = value

    @property
    def state(self):
        return self._state

    @state.setter
    def state(self, value):
        self._state = value

    @property
    def id(self):
        return self._id

    @id.setter
    def id(self, value):
        self._id = value

    @property
    def linked_key(self):
        return self._linked_key

    @linked_key.setter
    def linked_key(self, value):
        self._linked_key = value

    def to_pyson(self):
        pyson_object = {u'@odata.type': self._odata_type}
        self._add_pyson(pyson_object)
        return pyson_object

    def _add_pyson(self, pyson_object):
        pyson_object[u'displayName'] = self._display_name
        pyson_object[u'state'] = self._state
        pyson_object[u'id'] = self._id
        pyson_object[u'linkedKey'] = self._linked_key
        return pyson_object

    def from_pyson(self,pyson_object):
        self._parse_pyson(pyson_object)
        return pyson_object

    def _parse_pyson(self, pyson_object):
        if u'displayName' in pyson_object:
            self._display_name = pyson_object[u'displayName']

        if u'state' in pyson_object:
            self._state = pyson_object[u'state']

        if u'id' in pyson_object:
            self._id = pyson_object[u'id']

        if u'linkedKey' in pyson_object:
            self._linked_key = pyson_object[u'linkedKey']

        return pyson_object
# Odata Namespace Sel.Sel5056.Common.TrustAuthority.DataTreeObjects



class ExternalCertificateInfo(object):

    def __init__(self):
        self._odata_type = u'#Sel.Sel5056.Common.TrustAuthority.DataTreeObjects.ExternalCertificateInfo'
        self._name = u""
        self._base64_certificate = u""
        self._thumb_print = u""
        self._certificate_password = u""
        self._id = u""

    def from_json(self, json_string):
        pyson_object = json.loads(json_string)
        self.from_pyson(pyson_object)
        return self

    def to_json(self):
        pyson_object = self.to_pyson()
        json_string = json.dumps(pyson_object, sort_keys=True, indent=4, separators=(u',', u': '))
        return json_string

    _name = None
    _base64_certificate = None
    _thumb_print = None
    _certificate_password = None
    _purpose = None
    _id = None

    @property
    def name(self):
        return self._name

    @name.setter
    def name(self, value):
        self._name = value

    @property
    def base64_certificate(self):
        return self._base64_certificate

    @base64_certificate.setter
    def base64_certificate(self, value):
        self._base64_certificate = value

    @property
    def thumb_print(self):
        return self._thumb_print

    @thumb_print.setter
    def thumb_print(self, value):
        self._thumb_print = value

    @property
    def certificate_password(self):
        return self._certificate_password

    @certificate_password.setter
    def certificate_password(self, value):
        self._certificate_password = value

    @property
    def purpose(self):
        return self._purpose

    @purpose.setter
    def purpose(self, value):
        self._purpose = value

    @property
    def id(self):
        return self._id

    @id.setter
    def id(self, value):
        self._id = value

    def to_pyson(self):
        pyson_object = {u'@odata.type': self._odata_type}
        self._add_pyson(pyson_object)
        return pyson_object

    def _add_pyson(self, pyson_object):
        pyson_object[u'name'] = self._name
        pyson_object[u'base64Certificate'] = self._base64_certificate
        pyson_object[u'thumbPrint'] = self._thumb_print
        pyson_object[u'certificatePassword'] = self._certificate_password
        pyson_object[u'purpose'] = self._purpose
        pyson_object[u'id'] = self._id
        return pyson_object

    def from_pyson(self,pyson_object):
        self._parse_pyson(pyson_object)
        return pyson_object

    def _parse_pyson(self, pyson_object):
        if u'name' in pyson_object:
            self._name = pyson_object[u'name']

        if u'base64Certificate' in pyson_object:
            self._base64_certificate = pyson_object[u'base64Certificate']

        if u'thumbPrint' in pyson_object:
            self._thumb_print = pyson_object[u'thumbPrint']

        if u'certificatePassword' in pyson_object:
            self._certificate_password = pyson_object[u'certificatePassword']

        if u'purpose' in pyson_object:
            self._purpose = pyson_object[u'purpose']

        if u'id' in pyson_object:
            self._id = pyson_object[u'id']

        return pyson_object
# Odata Namespace Sel.Sel5056.Common.DataBroker.Types.EventBus



class Behavior(object):

    def __init__(self):
        self._odata_type = u'#Sel.Sel5056.Common.DataBroker.Types.EventBus.Behavior'

    def from_json(self, json_string):
        pyson_object = json.loads(json_string)
        self.from_pyson(pyson_object)
        return self

    def to_json(self):
        pyson_object = self.to_pyson()
        json_string = json.dumps(pyson_object, sort_keys=True, indent=4, separators=(u',', u': '))
        return json_string

    _behavior_type = None
    _severity = None

    @property
    def behavior_type(self):
        return self._behavior_type

    @behavior_type.setter
    def behavior_type(self, value):
        self._behavior_type = value

    @property
    def severity(self):
        return self._severity

    @severity.setter
    def severity(self, value):
        self._severity = value

    def to_pyson(self):
        pyson_object = {u'@odata.type': self._odata_type}
        self._add_pyson(pyson_object)
        return pyson_object

    def _add_pyson(self, pyson_object):
        pyson_object[u'behaviorType'] = self._behavior_type
        pyson_object[u'severity'] = self._severity
        return pyson_object

    def from_pyson(self,pyson_object):
        self._parse_pyson(pyson_object)
        return pyson_object

    def _parse_pyson(self, pyson_object):
        if u'behaviorType' in pyson_object:
            self._behavior_type = pyson_object[u'behaviorType']

        if u'severity' in pyson_object:
            self._severity = pyson_object[u'severity']

        return pyson_object


class EventType(object):

    def __init__(self):
        self._odata_type = u'#Sel.Sel5056.Common.DataBroker.Types.EventBus.EventType'
        self._type_key = TypeKey()
        self._id = u""

    def from_json(self, json_string):
        pyson_object = json.loads(json_string)
        self.from_pyson(pyson_object)
        return self

    def to_json(self):
        pyson_object = self.to_pyson()
        json_string = json.dumps(pyson_object, sort_keys=True, indent=4, separators=(u',', u': '))
        return json_string

    _type_key = None
    _duration_setting = None
    _severity = None
    _id = None

    @property
    def type_key(self):
        return self._type_key

    @type_key.setter
    def type_key(self, value):
        self._type_key = value

    @property
    def duration_setting(self):
        return self._duration_setting

    @duration_setting.setter
    def duration_setting(self, value):
        self._duration_setting = value

    @property
    def severity(self):
        return self._severity

    @severity.setter
    def severity(self, value):
        self._severity = value

    @property
    def id(self):
        return self._id

    @id.setter
    def id(self, value):
        self._id = value

    def to_pyson(self):
        pyson_object = {u'@odata.type': self._odata_type}
        self._add_pyson(pyson_object)
        return pyson_object

    def _add_pyson(self, pyson_object):
        pyson_object[u'typeKey'] = self._type_key.to_pyson()
        pyson_object[u'durationSetting'] = self._duration_setting
        pyson_object[u'severity'] = self._severity
        pyson_object[u'id'] = self._id
        return pyson_object

    def from_pyson(self,pyson_object):
        self._parse_pyson(pyson_object)
        return pyson_object

    def _parse_pyson(self, pyson_object):
        if u'typeKey' in pyson_object:
            self._type_key = pyson_object[u'typeKey']

        if u'durationSetting' in pyson_object:
            self._duration_setting = pyson_object[u'durationSetting']

        if u'severity' in pyson_object:
            self._severity = pyson_object[u'severity']

        if u'id' in pyson_object:
            self._id = pyson_object[u'id']

        return pyson_object


class EventCategory(object):

    def __init__(self):
        self._odata_type = u'#Sel.Sel5056.Common.DataBroker.Types.EventBus.EventCategory'
        self._key = u""
        self._behaviors = []
        self._id = u""

    def from_json(self, json_string):
        pyson_object = json.loads(json_string)
        self.from_pyson(pyson_object)
        return self

    def to_json(self):
        pyson_object = self.to_pyson()
        json_string = json.dumps(pyson_object, sort_keys=True, indent=4, separators=(u',', u': '))
        return json_string

    _key = None
    _behaviors = []
    _id = None

    @property
    def key(self):
        return self._key

    @key.setter
    def key(self, value):
        self._key = value

    @property
    def behaviors(self):
        return self._behaviors

    @behaviors.setter
    def behaviors(self, value):
        self._behaviors = value

    @property
    def id(self):
        return self._id

    @id.setter
    def id(self, value):
        self._id = value

    def to_pyson(self):
        pyson_object = {u'@odata.type': self._odata_type}
        self._add_pyson(pyson_object)
        return pyson_object

    def _add_pyson(self, pyson_object):
        pyson_object[u'key'] = self._key
        #Complex Copy of behaviors
        behaviors_result = []
        for item_from_behaviors in self._behaviors:
            behaviors_result.append(item_from_behaviors.to_pyson())
        pyson_object[u'behaviors'] = behaviors_result
        pyson_object[u'id'] = self._id
        return pyson_object

    def from_pyson(self,pyson_object):
        self._parse_pyson(pyson_object)
        return pyson_object

    def _parse_pyson(self, pyson_object):
        if u'key' in pyson_object:
            self._key = pyson_object[u'key']

        if u'behaviors' in pyson_object:
            self._behaviors = []
            behaviors_json_list = pyson_object[u'behaviors']
            for behaviors_json_element in behaviors_json_list:
                behaviors_odata_type = u'#Sel.Sel5056.Common.DataBroker.Types.EventBus.Behavior'
                if u'@odata.type' in behaviors_json_element:
                    behaviors_odata_type = behaviors_json_element[u'@odata.type']
                new_element = _ResolveOdataType.getNewObject(behaviors_odata_type)
                new_element.from_pyson(behaviors_json_element)
                self._behaviors.append(new_element)
        if u'id' in pyson_object:
            self._id = pyson_object[u'id']

        return pyson_object


class ClearedEventType(EventType):

    def __init__(self):
        super(ClearedEventType, self).__init__()
        self._odata_type = u'#Sel.Sel5056.Common.DataBroker.Types.EventBus.ClearedEventType'
        self._linked_type_key = TypeKey()

    def from_json(self, json_string):
        pyson_object = json.loads(json_string)
        self.from_pyson(pyson_object)
        return self

    def to_json(self):
        pyson_object = self.to_pyson()
        json_string = json.dumps(pyson_object, sort_keys=True, indent=4, separators=(u',', u': '))
        return json_string

    _linked_type_key = None

    @property
    def linked_type_key(self):
        return self._linked_type_key

    @linked_type_key.setter
    def linked_type_key(self, value):
        self._linked_type_key = value

    def to_pyson(self):
        pyson_object = {u'@odata.type': self._odata_type}
        super(ClearedEventType, self)._add_pyson(pyson_object)
        self._add_pyson(pyson_object)
        return pyson_object

    def _add_pyson(self, pyson_object):
        pyson_object[u'linkedTypeKey'] = self._linked_type_key.to_pyson()
        return pyson_object

    def from_pyson(self,pyson_object):
        super(ClearedEventType, self)._parse_pyson(pyson_object)
        self._parse_pyson(pyson_object)
        return pyson_object

    def _parse_pyson(self, pyson_object):
        if u'linkedTypeKey' in pyson_object:
            self._linked_type_key = pyson_object[u'linkedTypeKey']

        return pyson_object
# Odata Namespace Sel.Sel5056.Common.RestBroker.Models



class RestTransaction(object):

    def __init__(self):
        self._odata_type = u'#Sel.Sel5056.Common.RestBroker.Models.RestTransaction'
        self._id = u""

    def from_json(self, json_string):
        pyson_object = json.loads(json_string)
        self.from_pyson(pyson_object)
        return self

    def to_json(self):
        pyson_object = self.to_pyson()
        json_string = json.dumps(pyson_object, sort_keys=True, indent=4, separators=(u',', u': '))
        return json_string

    _id = None

    @property
    def id(self):
        return self._id

    @id.setter
    def id(self, value):
        self._id = value

    def to_pyson(self):
        pyson_object = {u'@odata.type': self._odata_type}
        self._add_pyson(pyson_object)
        return pyson_object

    def _add_pyson(self, pyson_object):
        pyson_object[u'id'] = self._id
        return pyson_object

    def from_pyson(self,pyson_object):
        self._parse_pyson(pyson_object)
        return pyson_object

    def _parse_pyson(self, pyson_object):
        if u'id' in pyson_object:
            self._id = pyson_object[u'id']

        return pyson_object
# Odata Namespace Sel.Sel5056.OpenFlowPlugin.Enums


class OfpActionType(object):

    @staticmethod
    def output():
        return u"Output"

    @staticmethod
    def copy_ttl_out():
        return u"CopyTtlOut"

    @staticmethod
    def copy_ttl_in():
        return u"CopyTtlIn"

    @staticmethod
    def set_mpls_ttl():
        return u"SetMplsTtl"

    @staticmethod
    def dec_mpls_ttl():
        return u"DecMplsTtl"

    @staticmethod
    def push_vlan():
        return u"PushVlan"

    @staticmethod
    def pop_vlan():
        return u"PopVlan"

    @staticmethod
    def push_mpls():
        return u"PushMpls"

    @staticmethod
    def pop_mpls():
        return u"PopMpls"

    @staticmethod
    def set_queue():
        return u"SetQueue"

    @staticmethod
    def group():
        return u"Group"

    @staticmethod
    def set_nw_ttl():
        return u"SetNwTtl"

    @staticmethod
    def dec_nw_ttl():
        return u"DecNwTtl"

    @staticmethod
    def set_field():
        return u"SetField"

    @staticmethod
    def push_pbb():
        return u"PushPbb"

    @staticmethod
    def pop_pbb():
        return u"PopPbb"

    @staticmethod
    def experimenter():
        return u"Experimenter"

class OfpInstructionType(object):

    @staticmethod
    def goto_table():
        return u"GotoTable"

    @staticmethod
    def write_metadata():
        return u"WriteMetadata"

    @staticmethod
    def write_actions():
        return u"WriteActions"

    @staticmethod
    def apply_actions():
        return u"ApplyActions"

    @staticmethod
    def clear_actions():
        return u"ClearActions"

    @staticmethod
    def meter():
        return u"Meter"

    @staticmethod
    def experimenter():
        return u"Experimenter"

class OfpGroupType(object):

    @staticmethod
    def all():
        return u"All"

    @staticmethod
    def select():
        return u"Select"

    @staticmethod
    def indirect():
        return u"Indirect"

    @staticmethod
    def fast_failover():
        return u"FastFailover"
# Odata Namespace Sel.Sel5056.TopologyManager


class State(object):

    @staticmethod
    def none():
        return u"None"

    @staticmethod
    def adopted():
        return u"Adopted"

    @staticmethod
    def unadopted():
        return u"Unadopted"

    @staticmethod
    def disconnected():
        return u"Disconnected"

    @staticmethod
    def established():
        return u"Established"

    @staticmethod
    def configured():
        return u"Configured"
# Odata Namespace Sel.Sel5056.Common.TrustAuthority.Enums


class CertificatePurpose(object):

    @staticmethod
    def web_server():
        return u"WebServer"

    @staticmethod
    def internal_certificate_authority():
        return u"InternalCertificateAuthority"
# Odata Namespace Sel.Sel5056.Common.DataBroker.Types.EventBus.Enums


class DurationType(object):

    @staticmethod
    def momentary():
        return u"Momentary"

    @staticmethod
    def persistent():
        return u"Persistent"

class SeverityLevel(object):

    @staticmethod
    def emergency():
        return u"Emergency"

    @staticmethod
    def alert():
        return u"Alert"

    @staticmethod
    def critical():
        return u"Critical"

    @staticmethod
    def error():
        return u"Error"

    @staticmethod
    def warning():
        return u"Warning"

    @staticmethod
    def notice():
        return u"Notice"

    @staticmethod
    def informational():
        return u"Informational"

    @staticmethod
    def debug():
        return u"Debug"

class BehaviorType(object):

    @staticmethod
    def alarm_request():
        return u"AlarmRequest"

    @staticmethod
    def local_log_data():
        return u"LocalLogData"

    @staticmethod
    def syslog_data():
        return u"SyslogData"

    @staticmethod
    def web_data():
        return u"WebData"
# Odata Namespace Sel


#
#Begin IOC Container Definition (Dependency Resolvers)
#
class _ResolveOdataType(object):

    @staticmethod
    def getNewObject(odata_type):
        result = None
        if odata_type == u"#Sel.Sel5056.Common.DataBroker.Types.TypeKey":
            result = TypeKey()
        elif odata_type == u"#Sel.Sel5056.OpenFlowPlugin.DataTreeObjects.Bucket":
            result = Bucket()
        elif odata_type == u"#Sel.Sel5056.OpenFlowPlugin.DataTreeObjects.Action":
            result = Action()
        elif odata_type == u"#Sel.Sel5056.OpenFlowPlugin.DataTreeObjects.GroupAction":
            result = GroupAction()
        elif odata_type == u"#Sel.Sel5056.OpenFlowPlugin.DataTreeObjects.OutputAction":
            result = OutputAction()
        elif odata_type == u"#Sel.Sel5056.OpenFlowPlugin.DataTreeObjects.PushVlanAction":
            result = PushVlanAction()
        elif odata_type == u"#Sel.Sel5056.OpenFlowPlugin.DataTreeObjects.PopVlanAction":
            result = PopVlanAction()
        elif odata_type == u"#Sel.Sel5056.OpenFlowPlugin.DataTreeObjects.Match":
            result = Match()
        elif odata_type == u"#Sel.Sel5056.OpenFlowPlugin.DataTreeObjects.Instruction":
            result = Instruction()
        elif odata_type == u"#Sel.Sel5056.OpenFlowPlugin.DataTreeObjects.ApplyActions":
            result = ApplyActions()
        elif odata_type == u"#Sel.Sel5056.OpenFlowPlugin.DataTreeObjects.GoToTable":
            result = GoToTable()
        elif odata_type == u"#Sel.Sel5056.OpenFlowPlugin.DataTreeObjects.WriteActions":
            result = WriteActions()
        elif odata_type == u"#Sel.Sel5056.OpenFlowPlugin.DataTreeObjects.Flow":
            result = Flow()
        elif odata_type == u"#Sel.Sel5056.OpenFlowPlugin.DataTreeObjects.Group":
            result = Group()
        elif odata_type == u"#Sel.Sel5056.OpenFlowPlugin.DataTreeObjects.FlowSet":
            result = FlowSet()
        elif odata_type == u"#Sel.Sel5056.TopologyManager.Nodes.ConfigNode":
            result = ConfigNode()
        elif odata_type == u"#Sel.Sel5056.TopologyManager.Ports.ConfigPort":
            result = ConfigPort()
        elif odata_type == u"#Sel.Sel5056.TopologyManager.Links.ConfigLink":
            result = ConfigLink()
        elif odata_type == u"#Sel.Sel5056.Common.TrustAuthority.DataTreeObjects.ExternalCertificateInfo":
            result = ExternalCertificateInfo()
        elif odata_type == u"#Sel.Sel5056.Common.DataBroker.Types.EventBus.Behavior":
            result = Behavior()
        elif odata_type == u"#Sel.Sel5056.Common.DataBroker.Types.EventBus.EventType":
            result = EventType()
        elif odata_type == u"#Sel.Sel5056.Common.DataBroker.Types.EventBus.EventCategory":
            result = EventCategory()
        elif odata_type == u"#Sel.Sel5056.Common.DataBroker.Types.EventBus.ClearedEventType":
            result = ClearedEventType()
        elif odata_type == u"#Sel.Sel5056.Common.RestBroker.Models.RestTransaction":
            result = RestTransaction()
        return result



